sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20040724

  alioss:
    #华北2
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: javaspring-ai0909

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wx298aa170352cb1c9
    secret: d596e46149fa9af31c8b38f38a08fa01